#!/bin/bash

# --------------------- CONFIG SECTION ---------------------
# this can be hardcoded
GIT_REMOTE_ORIGIN=$(git config --get remote.origin.url)
JOBS_TO_KEEP=5
#CI_SERVER=https://ci.example.com:8080
# --------------------- CONFIG SECTION [END]----------------






# ANSI color codes
RS="\033[0m"    # reset
HC="\033[1m"    # hicolor
UL="\033[4m"    # underline
INV="\033[7m"   # inverse background and foreground
FBLK="\033[30m" # foreground black
FRED="\033[31m" # foreground red
FGRN="\033[32m" # foreground green
FYEL="\033[33m" # foreground yellow
FBLE="\033[34m" # foreground blue
FMAG="\033[35m" # foreground magenta
FCYN="\033[36m" # foreground cyan
FWHT="\033[37m" # foreground white
BBLK="\033[40m" # background black
BRED="\033[41m" # background red
BGRN="\033[42m" # background green
BYEL="\033[43m" # background yellow
BBLE="\033[44m" # background blue
BMAG="\033[45m" # background magenta
BCYN="\033[46m" # background cyan
BWHT="\033[47m" # background white

read -r -d '' splash <<EOF
${FMAG}♥${RS}



             _            ${FGRN} _${RS}    _ _   
            (_)_   _ _ __ ${FGRN}| | _${RS}(_) |_ 
            | | | | | '_ \\\\${FGRN}| |/ /${RS} | __|
            | | |_| | | | ${FGRN}|   <${RS}| | |_ 
           _/ |\__,_|_| |_${FGRN}|_|\_\\\\${RS}_|\__|
          |__/

                        for support: ysoheil@gmail.com
                        
                        bin/junkit [JOB_NAME] [BRANCH_NAME]
                        -v for verbose mode


EOF
echo -e "$splash"
echo "Starting up..."

SINGLE_SPEC=""
while getopts "s:" opt; do
    case "$opt" in
    s)  SINGLE_SPEC="$OPTARG"
        ;;
    esac
done

if [[ "$1" != "" && "$1" != "-v" && "$1" != "-s" ]]; then
  WHOAMI="$1"
else
  WHOAMI=`whoami`
fi

SAFE_CI_SERVER="http://$CI_SERVER"
CI_SERVER="http://$LOGIN@$CI_SERVER"

if [[ "$1" != "-s" && "$2" != "" ]]; then
  GIT_BRANCH="$2"
else
  GIT_BRANCH=$(git branch|grep \*|sed -e "s/\* //")
fi

if [[ "$SINGLE_SPEC" == "" ]]; then
  JOB_NAME=$(echo "$WHOAMI"_"$GIT_BRANCH" | awk '{print tolower($0)}')
else
  JOB_NAME=$(echo "$WHOAMI"_"single_spec" | awk '{print tolower($0)}')
fi
if [ "${#JOB_NAME}" -gt 50 ]; then
  JOB_NAME=$(echo "$JOB_NAME" | md5)
  JOB_NAME="$WHOAMI"_${JOB_NAME:0:5}
  echo -e "${BYEL}Job name too long, changed to: $JOB_NAME${RS}"
fi
curl -s -o /dev/null -X POST "$CI_SERVER/job/$JOB_NAME/doDelete"
echo "Creating Job for current branch..."

# replace \n with ;\n (this is the "tr") - escape string (this is the "sed")
COMMAND_TO_EXECUTE=$(tr '\n' ';' < $(dirname "$0")/command_to_execute.sh | sed -e 's/[\/&]/\\&/g' | sed -e 's/;;/;/g')
GIT_REMOTE_ORIGIN=$(echo "$GIT_REMOTE_ORIGIN" | sed -e 's/[\/&]/\\&/g')
cat $(dirname "$0")/config.xml | sed -e "s/COMMAND_TO_EXECUTE/$COMMAND_TO_EXECUTE/" | sed -e "s/GIT_BRANCH/$GIT_BRANCH/g" | sed -e "s/JOB_NAME/$JOB_NAME/g" | sed -e "s/GIT_REMOTE_ORIGIN/$GIT_REMOTE_ORIGIN/g" | sed -e "s:SINGLE_SPEC:$SINGLE_SPEC:g" > /tmp/config-tmp.xml

curl -X POST -d @/tmp/config-tmp.xml -H "Content-Type:text/xml" "$CI_SERVER/createItem?name=$JOB_NAME"
echo "Starting a build..."
curl -X POST "$CI_SERVER/job/$JOB_NAME/build"
echo -e "${FGRN}Scheduled build:\n\n\n\t\t\t ${FCYN}$SAFE_CI_SERVER/job/$JOB_NAME/lastBuild/console${RS}\n\n\n"

echo "Started at: $(date)"
if [[ "$1" == "-v" ]]; then
  printf "Fetching logs"
else
  echo "Waiting for build to finish... (or CTRL+C to exit and leave the build running)"
fi

# do some clean up, while we're waiting
echo "$JOB_NAME" >> ~/.junkit_jobs
# uniq file inplace
{ rm ~/.junkit_jobs && uniq > ~/.junkit_jobs; } < ~/.junkit_jobs
if [ "$(cat ~/.junkit_jobs | wc -l)" -gt "$JOBS_TO_KEEP" ]; then
  # get the first line from the file
  JOB_NAME_TO_DELETE="$(head -1 ~/.junkit_jobs)"
  # remove the first line in the file
  { rm ~/.junkit_jobs && tail -n +2 > ~/.junkit_jobs; } < ~/.junkit_jobs
  if [[ "$JOB_NAME" != "$JOB_NAME_TO_DELETE" ]]; then
    curl -s -o /dev/null -X POST "$CI_SERVER/job/$JOB_NAME_TO_DELETE/doDelete"
  fi
fi

printedNewLineOnce=0
printedRunningSpecsOnce=0
allOut=""
while [[ ! "$out" =~ "Finished: " ]]; do
  if [ ! -n "$start" ]; then
    start=0
  fi
  out=$(curl -D /tmp/header.file -s "$CI_SERVER/job/$JOB_NAME/lastBuild/logText/progressiveHtml?start=$start")
  start=$(cat /tmp/header.file|grep "X-Text-Size"|cut -f2 -d:|sed 's/ //')
  allOut="$allOut\n$out"

  if [[ $printedRunningSpecsOnce == 0 && "$out" =~ "Execute spec" ]]; then
    echo "Running specs..."
    printedRunningSpecsOnce=1
  fi

  # verbose only after this point
  if [[ "$1" != "-v" ]]; then
    continue
  fi
  if [[ "$out" =~ "Status Code: 404" ]]; then
    printf "."
  else
    if [[ $printedNewLineOnce == 0 ]]; then
      echo ""
      printedNewLineOnce=1
    fi
    if [ -n "$out" ]; then
      echo "$out"
    fi
  fi
  sleep 1
done

if [[ "$out" =~ "Finished: FAILURE" ]]; then
  echo -e "\n\n-------------------------------------------------------"
  echo -e " FAILURE LOG"
  echo -e "-------------------------------------------------------\n\n"

  # get top half
  if [[ "$allOut" =~ " failure" ]]; then
    osascript -e 'display notification "Build Failed! Sorry:(" with title "Build Status"'
    echo -e "Getting logs..."
    allOut=$(curl -s "$CI_SERVER/job/$JOB_NAME/lastBuild/consoleText")

    lineNumber=$(echo "$allOut"|grep -n "Failed examples:"|cut -f1 -d:)
    allOut=$(echo "$allOut"|head -n$(($lineNumber - 2)))

    # get bottom half
    lineNumber=$(($(echo "$allOut"|wc -l|sed 's/ //g') - $(echo "$allOut"|grep -n "Failures:"|cut -f1 -d:)))
    allOut=$(echo "$allOut"|tail -n$(($lineNumber)))

    echo -e "$allOut"
  else
    echo "No tests to report"
  fi

  echo -e "${FRED}\n\nFailed!${RS}\n\n"
  exit 1
fi

if [[ "$out" =~ "Finished: SUCCESS" ]]; then
  # build time
  echo "$out" | grep "Finished in"

  # success, failure count
  echo "$out" | grep " failures,"
  echo -e "${FGRN}\nSucceeded!${RS}\n\n"
  osascript -e 'display notification "Build Succeeded! Yay!!" with title "Build Status"'
  exit 0
fi